### ISSUE TITLE
install dependency failed on Colab

### ISSUE THREAD

**Issue by Minou43** [modelscope/ClearerVoice-Studio#1]
I try to build this project on Colab but dependency install failed, is there a problem with requirements.txt?

here's the code I run on Colab:

`!git clone https://github.com/modelscope/ClearerVoice-Studio.git`
`%cd ClearerVoice-Studio`
`!pip install -r requirements.txt`

here's the error message:
Collecting torch==2.0.1 (from -r requirements.txt (line 1))
  Downloading torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl.metadata (24 kB)
Collecting pesq==0.0.4 (from -r requirements.txt (line 2))
  Downloading pesq-0.0.4.tar.gz (38 kB)
  Preparing metadata (setup.py) ... done
Collecting pystoi==0.3.3 (from -r requirements.txt (line 3))
  Downloading pystoi-0.3.3.tar.gz (7.0 kB)
  Preparing metadata (setup.py) ... done
Collecting pyyaml==5.4.1 (from -r requirements.txt (line 4))
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 7.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Minou43** [comment]
BTY, does this model work on unseen speakers?

**Comment by Minou43** [comment]
it seems that colab has build issue with that version of pyyaml, is is possible to use pyyaml v6?

**Comment by alibabasglab** [comment]
> it seems that colab has build issue with that version of pyyaml, is is possible to use pyyaml v6?

Hi Minou43, thank you for your trying on platform. We believe pyyaml v6 should be working fine as long as this version is installed successfully.

**Comment by alibabasglab** [comment]
> BTY, does this model work on unseen speakers?

Yes, it works on unseen speakers.
