### ISSUE TITLE
huggingface的webui本地运行报错

### ISSUE THREAD

**Issue by Jandown** [modelscope/ClearerVoice-Studio#12]
前两个音频增强和语音分离都正常，第三个，Task 3: Audio-Visual Speaker Extraction，提交就报错
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'path_to_output_videos_tse\\AV_MossFormer2_TSE_16K/C:'

请问这个怎么解决，试过重新拼接路径还是报错

**Comment by zexupan** [comment]
目前支持.mp4 .avi .mov .webm 格式的视频，请问一下你的视频是这些格式吗，还是什么格式呀。

如果huggingface不行，clone 这个repo本地跑也会这样报错吗？

**Comment by Jandown** [comment]
用的是自带的两个视频，本地还没测试。
这个支持win吗？

**Comment by minguo** [comment]
你这个是在windows下运行,他分离路径分隔符的时候,按linux的分隔符去写死

你搜索video_process.py
# savFolder = videoPath.split('/')[-1]
savFolder = videoPath.split(os.path.sep)[-1]

改成我给的代码就可以解决

**Comment by Jandown** [comment]
> 你这个是在windows下运行,他分离路径分隔符的时候,按linux的分隔符去写死
> 
> 你搜索video_process.py
> 
> # savFolder = videoPath.split('/')[-1]
> savFolder = videoPath.split(os.path.sep)[-1]
> 
> 改成我给的代码就可以解决

感谢回复，第一个路径的问题已经解决了
现在是使用task3出现 soundfile.LibsndfileError: Error opening 'path_to_output_videos_tse\\AV_MossFormer2_TSE_16K/001/py_faceTracks\\py_faceTracks\\00000.wav'
的错误，很明显，多了一层py_faceTracks，这个始终没搞明白哪里多出了一层py_faceTracks

**Comment by Jandown** [comment]
确实很多命令也是linux的写法，上面的问题解决了，也替换了几个linux上的命令，现在是可以生成了，但输出窗口不显示，看了本地是生成成功的。

**Comment by zexupan** [comment]
不好意思我们代码是在linux下面开发的，一开始没考虑到windows的用户，已经修改了videoPath.split('/')[-1] 这个代码。 但是我看video_process.py 里面还有好多文件路径命名是linux的方式，所以windows可能报错了，你可以尝试更改一下。我们没配备windows电脑，不能在windows下面调试，有点怕忙改也会出一堆bug。

Task3 会输出两个文件夹，py_video 和 py_faceTracks。

**Comment by Jandown** [comment]
> 不好意思我们代码是在linux下面开发的，一开始没考虑到windows的用户，已经修改了videoPath.split('/')[-1] 这个代码。 但是我看video_process.py 里面还有好多文件路径命名是linux的方式，所以windows可能报错了，你可以尝试更改一下。我们没配备windows电脑，不能在windows下面调试，有点怕忙改也会出一堆bug。
> 
> Task3 会输出两个文件夹，py_video 和 py_faceTracks。

好多，感谢作者。希望后期能兼容下win，毕竟很多用户尤其是小白还是喜欢在win上测试使用，再次感谢。

**Comment by zexupan** [comment]
感谢支持，同时我们也welcome contributor哈，有意向可以一起帮忙改进这个代码。
