### ISSUE TITLE
为啥不把gradio的UIdemo也给一下?

### ISSUE THREAD

**Issue by minguo** [modelscope/ClearerVoice-Studio#14]
这样本地调试才方便啊大哥,,,hf上有,代码里面又不给

**Comment by Jandown** [comment]
这个可以有

**Comment by alibabasglab** [comment]
请问代码里面缺少哪些部分呢？我们代码提供的模型和demo里面是一样的

**Comment by minguo** [comment]
没少,github上的代码没有hf上app.py ,我自己在hf上下载了

**Comment by Jandown** [comment]
> 没少,github上的代码没有hf上app.py ,我自己在hf上下载了

hf的demo你本地clone下来能跑吗？
我还是task3跑不起来，昨晚折腾了一宿，输出不显示视频，实际数出来的是视频，但是显示是图片

**Comment by zexupan** [comment]
Merged this issue to:  huggingface的webui本地运行报错 #12
