### ISSUE TITLE
背景带有笑声的增强效果较差

### ISSUE THREAD

**Issue by lucasjinreal** [modelscope/ClearerVoice-Studio#2]
不太确定背景带有观众笑声的音频，有什么办法可以只抽取说话人的声音吗？目前试了官方demo，笑声几乎无法得到抑制

理论上来讲，背景中与说话人无关的声音，应该也是噪声的一种。

**Comment by alibabasglab** [comment]
请问你试用的是48K的模型吗？我们测试中是可以很好的控制笑声的。

**Comment by alibabasglab** [comment]
但是，如果是说话人笑着讲话，应该会是保留的。

**Comment by lucasjinreal** [comment]
感谢，我换了几段音频试了一下，如果是笑声事混在说话声音一起的，可以得到很好的抑制。
但是如果是结尾一部分笑声与说话人声没有混合，则无法处理。

这种情况是不是当成了说话人声的一部分了？

**Comment by alibabasglab** [comment]
是的，模型可能误识别成语音了，这种情况对数据要求较高，我们也在尝试想办法解决
