### ISSUE TITLE
人脸模型找不到

### ISSUE THREAD

**Issue by 17will** [modelscope/ClearerVoice-Studio#20]
No such file or directory: ../ClearerVoice-Studio/clearvoice/models/av_mossformer2_tse/faceDetector/s3fd/sfd_face.pth

去了README里对应的链接找了下，是个谷歌网盘链接，访问不到了

**Comment by wangsrGit119** [comment]
安装下依赖：
```
gdown==5.2.0
```
重新启动会自动下载

**Comment by zexupan** [comment]
Updated the requirement file. Thanks.
