### ISSUE TITLE
输入4s的音频，为什么会输出14s的音频？？？

### ISSUE THREAD

**Issue by DogeFlow** [modelscope/ClearerVoice-Studio#22]
输入4s的音频，为什么会输出14s的音频？？？
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/3f8dc211-0555-4ef7-8eb1-43e3684fbe7c">

**Comment by DogeFlow** [comment]
这项目真的一言难尽...，测好了再放出来行吗，耽误时间

**Comment by minguo** [comment]
你的音频应该是立体声的,要单声道音频,你拿个音频软件转一下就可以了,他处理立体声会有这个问题

**Comment by wwfcnu** [comment]
> 你的音频应该是立体声的,要单声道音频,你拿个音频软件转一下就可以了,他处理立体声会有这个问题

看读数据的时候，它做了转单通道的

**Comment by yuantuo666** [comment]
也遇到了一样的问题，在用 16kHz 模型处理多声道的高采样率音频就会出现这个问题
代码实现有 bug，可以参考这个 PR 进行修复 https://github.com/modelscope/ClearerVoice-Studio/pull/37
