### ISSUE TITLE
dataloader报错

### ISSUE THREAD

**Issue by sklongger** [modelscope/ClearerVoice-Studio#38]
local variable 'audio' referenced before assignment

**Comment by 25sunyao** [comment]
Replace ‘audio’ with ‘data’.

**Comment by 25sunyao** [comment]
> local variable 'audio' referenced before assignment

Replace ‘audio’ with ‘data’.

**Comment by zexupan** [comment]
Can you please let us know which part of the code returns error so that we can fix it? Thanks.

**Comment by 25sunyao** [comment]
> Can you please let us know which part of the code returns error so that we can fix it? Thanks.

dataloader/dataloader.py audioread

**Comment by gotoolkits** [comment]
Yes, replace 'audio' with 'data' in dataloader.py.

    // ...
    # convert to mono channel
    # if len(audio.shape) >1:
    #     if audio.shape[0] > audio.shape[1]:
    #         audio = audio[:, 0] 
    #     else:
    #         audio = audio[0, :] 
    if len(data.shape) >1:
        if data.shape[0] > data.shape[1]:
            data = data[:, 0] 
        else:
            data = data[0, :]

**Comment by zexupan** [comment]
Thanks @gotoolkits , updated the code.
